# vim: ai et ts=2 st=2 sw=2 :
---
- name: Check if we are running supported os
  ansible.builtin.assert:
    fail_msg: "{{ role_name }} only supports ubuntu versions 16, 18, 20, 22, centos versions 7, and rhel version 8!"
    success_msg: "{{ role_name }} supports {{ ansible_distribution }} version {{ ansible_distribution_version }}"
    quiet: "{{ not ansible_check_mode }}"
    that:
      ( ansible_distribution|lower == "ubuntu" and ansible_distribution_version|int in [ 16, 18, 20, 22] )
      or ( ansible_distribution|lower == "centos" and ansible_distribution_major_version|int in [7] )
      or ( ansible_distribution == "RedHat" and ansible_distribution_major_version|int in [8] )

# Configure repos before installing packages

- name: Include os specific config
  ansible.builtin.include: '{{ ansible_os_family | lower }}.yml'

- name: Install packages on both systems
  ansible.builtin.package:
    name: '{{ packages_install }}'
    state: present

- name: Services to start and enable on boot
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop: '{{ packages_services_enabled }}'

- name: Services to stop and disable on boot
  ansible.builtin.service:
    name: '{{ item }}'
    state: stopped
    enabled: false
  loop: '{{ packages_services_disabled }}'
